name: ci-workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: welcome steps
        run: echo "Welcome to the Github Actions"
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Repository Information
        run: |
          echo "Following is the Information About the Cloned Repo"
          echo "Repository Name: ${{github.repository}}"
          echo "Repository Owner: ${{github.owner}}"